### ISSUE TITLE
Do a top-level review of function and argument consistency

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/zoltpy#14]
Ok, If @nick approves, can I recommend that Khoa Le and khouse do a review of the zoltpy code for consistency? I.e., upload and download forecast should both work with the same format), and where should *zoltar json* vs. *zoltar csv* vs. *cdc csv* be passed? Also, the code in `create_project_app.py` to create a project should be moved to a new `ZoltarConnection.create_project()` function.

Part of this should be to make a decision re: whether the `util.py` functions take json or cdc csv.

We should also review where testing is important but missing. We can talk about "too simple to fail".

In addition, we should start thinking about Katie's idea to provide library consistency between zoltpy and zoltr. To that end, here are the current zoltr functions:

```
new_connection <- function(host="https://zoltardata.com")  # returns a ZoltarConnection instance
zoltar_authenticate <- function(zoltar_connection, username, password)

projects <- function(zoltar_connection)  # Get information about all projects as a data.frame
project_info <- function(zoltar_connection, project_id)  # Get information about a project as a list
scores <- function(zoltar_connection, project_id)  # Get a project's scores as a data.frame
models <- function(zoltar_connection, project_id)  # Get a project's models as a data.frame

model_info <- function(zoltar_connection, model_id)  # Get information about a model as a list
forecasts <- function(zoltar_connection, model_id)  # Get a model's forecasts as a data.frame
upload_forecast <- function(zoltar_connection, model_id, timezero_date, forecast_json_file)
delete_forecast <- function(zoltar_connection, forecast_id)  # Delete a forecast

forecast_info <- function(zoltar_connection, forecast_id)  # Gets a forecast's information as a list
forecast_data <- function(zoltar_connection, forecast_id)  # Gets a forecast's data as a list (json)
forecast_data_as_frame <- function(the_forecast_data)  # Converts forecast data from Zoltar's native list (json) format to a data.frame

upload_info <- function(zoltar_connection, upload_file_job_id)  # Get an upload's information as a list
```

These are all functions similar to zoltpy's `util` functions, and all take database IDs, except for the ZoltarConnection class, which is an object. Nick and I thought it was cleaner and easier to have users think about IDs (vs. URLs vs. objects). Also, we decided against classes other than connections because working with lists and data.frames seemed more R-like.

**Comment by nickreich** [comment]
1. download/upload functions in zoltR/zoltpy that interface with the Zoltar server directly should only accept predx-style json data objects.

2. there should be an additional utility function in each of zoltR/zoltpy that can translate from a predx-style json forecast into and from a CDC-style csv. 

upload use case: we have a CDC-csv file that we want to upload (or maybe a bunch of them). We run our utility function to make this a predx-style json file. Then we upload using generic upload function.

**Comment by matthewcornell** [comment]
note that nick's comment intentionally does not mention the non-cdc zoltar csv format. that's b/c we don't need to support it yet - our use case only involves the zoltar json <-> cdc csv formats.

**Comment by katiehouse3** [comment]
@nickreich @matthewcornell Khoa and I took a stab at updating the upload function! Here is an example of uploads:

## Example of upload function update
```
project_name = 'private project'
model_name = 'Test ForecastModel1'
timezero_date = '20170117'
forecast_file_path = 'tests/EW1-KoTsarima-2017-01-17-small.csv'

forecast_filename, predx_json = util.convert_cdc_csv_to_predx_json(forecast_file_path)
conn = util.authenticate()
util.upload_forecast(conn, predx_json, forecast_filename, project_name, model_name, timezero_date, overwrite=True)
```

## Our Updates:
1. we added the function `util.convert_cdc_csv_to_predx_json()` function to convert from CDC CSV --> predx json (with the help of Matt's previous work!)
2. we updated the `util.upload_forecast(...)` function to only accept the predx json files
3. we added a `util.upload_forecast(..., overwrite=True)` in case there are uploads of the same timezero

## Next Steps:
1. Run tests on the new upload function
2. Create an error handler in case predx json is accidentally not used

**Comment by katiehouse3** [comment]
Updates based on Matt's suggestions:

### code updates:
- [X] The return arg filepath should be just the file name, but it returns the passed arg as-is, which could include the path. This is wrong because it's what appears on the site. I use https://docs.python.org/3/library/pathlib.html for this kind of operation - see the examples elsewhere in zoltpy, e.g.,
 filepath = Path(filepath)
 ...
 return filepath.name
- [X] Its return arg tuple order (filepath, cdc_json) should be consistent with that of upload_forecast() (conn, predx_json, forecast_filename, ...)
Consistent variable names:
- [X] upload_forecast(): takes forecast_predx_json but download_forecast() returns a json_io_dict. Let's use json_io_dict consistently.
- [X] The variable cdc_json in convert_cdc_csv_to_predx_json() should be something like  json_io_dict (you can tell this from json_io_dict_from_cdc_csv_file()'s name - a tiny little code naming calculus).
- [X] upload_forecast()'s forecast_predx_json arg docs say it's a file, but really it's a JSON dict. Also, it still references cdc csv.
- [X] upload_forecast()'s overwrite arg is not documented.
- [X] authenticate(): uses "Connection" for a variable, but in python, variables are lower case (with underscores). Also, the code uses "conn" for that variable everywhere else, so this function should match.
- [X] the number of lines between functions: should be two, but the new util.py ones are sometimes three and sometimes one
- [X] upload_forecast()'s final two args extend past column 120 (data_version_date and overwrite should be on a new line)


### TODOS
- [ ] README.md should describe authenticate() and convert_cdc_csv_to_predx_json(), which are important, are used in an example, but mentioned no where else. (We need to add a section to README.md that describes the zoltar JSON format a little, including that it's the format handled by the server for uploads and downloads, and that we provide functions to convert to/from cdc csv. I haven't done this properly yet in the server source, but my first stab is at https://github.com/reichlab/forecast-repository/blob/master/utils/forecast.py ("JSON input/output format documentation"). I'll add an issue.)
- [ ] README.md should list download_forecast() as a top level function.
- [ ] similarly, README.md should have two lines between "##" sections as well
- [ ] All user-facing functions should have code documentation, and it should be correct.
- [ ] util.py: authenticate(), print_projects(), and convert_cdc_csv_to_predx_json() are undocumentated

**Comment by mzorn-58** [comment]
@nickreich Should this be closed?

**Comment by Khoale1096** [comment]
I did a review and marked any TODOs listed by Katie that was done. There are two last TODOs that might need to be done:

- **Add a section to README.md that describes the zoltar JSON format**: I think this section can just point towards this detailed documentation on Zoltar's File [Format](https://docs.zoltardata.com/fileformats/#forecast-data-format-json)
- **Create convert_json_io_dict_to_cdc_csv_file(json_io_dict, forecast_file_path) for download_forecast() use case**: This method is not yet implemented, but we have the method `util.dataframe_from_json_io_dict()` that converts the json to a pandas dataframe, which can then be converted to a csv with pandas `df.to_csv()`. But I believe this csv is not in the same format with the cdc csv. I think this TODO can be put into an entirely new issue on its own, and therefore close this issue.

**Comment by matthewcornell** [comment]
Sounds great!
